import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';

function Disclaimer() {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="legal-page">
            <nav className="legal-nav">
                <Link to="/" className="legal-back">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
                    Back to Home
                </Link>
                <div className="legal-logo">finova</div>
            </nav>

            <div className="legal-content">
                <h1 className="legal-title">Legal Disclaimer</h1>
                <p className="legal-updated">Last Updated: April 29, 2026</p>
                
                <div className="legal-section">
                    <p>The information provided on this platform (“Service”) is for <strong>informational and educational purposes only</strong> and does not constitute financial, investment, legal, or tax advice.</p>
                </div>

                <div className="legal-section">
                    <p>We are not registered with the Securities and Exchange Board of India as an investment advisor. The content generated by our AI systems is based on user-provided data, publicly available information, and predefined models, and may not be accurate, complete, or up to date.</p>
                </div>

                <div className="legal-section">
                    <h2>No Professional Advice</h2>
                    <p>Nothing on this platform should be interpreted as a recommendation to buy, sell, or hold any financial instrument. Users should consult a qualified and registered financial advisor before making any investment decisions.</p>
                </div>

                <div className="legal-section">
                    <h2>No Guarantees</h2>
                    <p>We do not guarantee any specific financial outcome, accuracy of predictions or projections, or profit/avoidance of losses. All investments involve risk, including potential loss of principal.</p>
                </div>

                <div className="legal-section">
                    <h2>User Responsibility</h2>
                    <p>You acknowledge that you are solely responsible for your financial decisions and that you use this platform at your own risk.</p>
                </div>

                <div className="legal-section">
                    <h2>Limitation of Liability</h2>
                    <p>To the fullest extent permitted by law, we shall not be liable for any financial losses, indirect or consequential damages, or decisions made based on the platform’s outputs.</p>
                </div>

                <div className="legal-section">
                    <h2>Third-Party Data</h2>
                    <p>The platform may rely on data from third-party sources. We do not guarantee the accuracy or reliability of such data.</p>
                </div>

                <div className="legal-section">
                    <h2>Changes</h2>
                    <p>We reserve the right to modify this disclaimer at any time without prior notice.</p>
                </div>

                <div className="legal-section">
                    <p>By using this platform, you agree to this disclaimer.</p>
                </div>
            </div>
        </div>
    );
}

export default Disclaimer;
